# -*- coding: utf-8 -*-
"""Colour Palette Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4nJtt0dFTI--8_S7-z1DQWkSR8kGPgZ
"""

# Import Necessary packages
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.cluster import KMeans

def rgb_to_hex(rgb):
    """Converts an RGB tuple (e.g., (255, 0, 0)) to a Hex code (e.g., #FF0000)."""
    return '#{:02x}{:02x}{:02x}'.format(int(rgb[0]), int(rgb[1]), int(rgb[2]))

def get_image_palette(image_path, n_colors=5):
    # 1. Load image
    img = mpimg.imread(image_path)

    # SAFETY CHECK: Handle PNGs (0-1 float) vs JPGs (0-255 int)
    # If the image is float, scale it up to 0-255 integers
    if img.dtype == np.float32 or img.dtype == np.float64:
        img = (img * 255).astype(int)

    # SAFETY CHECK: Remove Alpha channel if present (keep only RGB)
    if img.shape[-1] == 4:
        img = img[:, :, :3]

    # 2. Reshape the matrix to (-1, 3) for a single column of pixels
    pixel_list = img.reshape(-1, 3)

    # 3. Fit K-Means
    kmeans = KMeans(n_clusters=n_colors, random_state=42, n_init=10)
    kmeans.fit(pixel_list)

    # 4. Retrieve colours by cluster centers
    centers = kmeans.cluster_centers_
    dominant_colors = centers.astype(int)

    # 5. Convert to Hex for web use
    hex_palette = [rgb_to_hex(color) for color in dominant_colors]

    return hex_palette, dominant_colors

def visualise_palette(hex_palette, rgb_colors):
    plt.figure(figsize=(8, 2))
    plt.axis('off')
    plt.title(f"Extracted Palette")
    # Wrap rgb_colors in another list to create a 1-row image
    plt.imshow([rgb_colors], aspect='auto')
    plt.show()

# Readability function
def get_contrast_color(rgb_tuple):
    """Returns 'Black' or 'White' text color based on background luminance."""
    r, g, b = rgb_tuple
    # Calculate luminance (Standard Rec. 709)
    luminance = (0.2126 * r) + (0.7152 * g) + (0.0722 * b)

    if luminance > 128:
        return "Black (#000000)"
    else:
        return "White (#FFFFFF)"

# --- RUN CODE ---

# Replace with the actual image path
image_path = 'my_image.jpg'

try:
    hex_codes, rgb_values = get_image_palette(image_path)

    print(f"{'Color (Hex)':<15} | {'Recommended Font Color'}")
    print("-" * 45)

    for i in range(len(hex_codes)):
        hex_code = hex_codes[i]
        rgb = rgb_values[i]
        text_color = get_contrast_color(rgb)
        print(f"{hex_code:<15} | {text_color}")

    visualise_palette(hex_codes, rgb_values)

except FileNotFoundError:
    print(f"Error: The file '{image_path}' was not found. Please check the path.")